import React from 'react'

interface PageConfig {
  name: string
  title: string
  content: string[]
}

const pages: PageConfig[] = [
  {
    name: 'Jsx',
    title: '2. JSX 语法',
    content: [
      'JSX 是 JavaScript 的语法扩展，允许在 JavaScript 中编写类似 HTML 的代码。',
      '核心要点：',
      '- JSX 最终会被编译为 React.createElement() 调用',
      '- 可以使用花括号 {} 嵌入 JavaScript 表达式',
      '- 属性使用驼峰命名（className, onClick 等）',
      '- 必须有一个根元素包裹所有内容',
      '- 自闭合标签必须以 /> 结尾',
    ],
  },
  {
    name: 'Components',
    title: '3. 组件基础',
    content: [
      '组件是 React 应用的基本构建块。',
      '两种组件类型：',
      '- 函数组件：使用普通 JavaScript 函数定义',
      '- 类组件：使用 ES6 class 定义（现在较少使用）',
      '组件特点：',
      '- 可复用：同一组件可在多处使用',
      '- 可组合：组件可以嵌套组合',
      '- 独立：每个组件管理自己的状态和逻辑',
    ],
  },
  {
    name: 'PropsState',
    title: '4. Props 与 State',
    content: [
      'Props（属性）：',
      '- 从父组件传递给子组件的数据',
      '- 只读，子组件不能修改 props',
      '- 用于配置组件的行为和外观',
      '',
      'State（状态）：',
      '- 组件内部管理的可变数据',
      '- 使用 useState Hook 管理（函数组件）',
      '- 状态变化会触发组件重新渲染',
      '- 用于处理用户交互和动态数据',
    ],
  },
  {
    name: 'Events',
    title: '5. 事件处理',
    content: [
      'React 事件处理与原生 DOM 事件类似，但有一些区别：',
      '- 事件名使用驼峰命名（onClick, onChange 等）',
      '- 传递函数作为事件处理器，而不是字符串',
      '- 事件对象是合成事件（SyntheticEvent）',
      '- 需要绑定 this（类组件）或使用箭头函数',
      '',
      '常见事件：',
      '- onClick：点击事件',
      '- onChange：输入变化事件',
      '- onSubmit：表单提交事件',
      '- onMouseEnter/Leave：鼠标悬停事件',
    ],
  },
  {
    name: 'HooksIntro',
    title: '6. Hooks 入门',
    content: [
      'Hooks 是 React 16.8 引入的新特性，让函数组件可以使用状态和其他 React 特性。',
      '',
      '常用 Hooks：',
      '- useState：管理组件状态',
      '- useEffect：处理副作用（数据获取、订阅等）',
      '- useContext：访问 Context',
      '- useReducer：复杂状态管理',
      '- useCallback：记忆化回调函数',
      '- useMemo：记忆化计算结果',
      '- useRef：访问 DOM 或保存可变值',
      '',
      'Hook 规则：',
      '- 只在顶层调用 Hook（不能在循环、条件或嵌套函数中）',
      '- 只在 React 函数组件或自定义 Hook 中调用',
    ],
  },
  {
    name: 'UseEffect',
    title: '7. useEffect Hook',
    content: [
      'useEffect 用于在函数组件中执行副作用操作。',
      '',
      '基本用法：',
      '- useEffect(() => { ... })：每次渲染后执行',
      '- useEffect(() => { ... }, [])：仅在挂载时执行（类似 componentDidMount）',
      '- useEffect(() => { ... }, [dep])：依赖变化时执行（类似 componentDidUpdate）',
      '',
      '清理函数：',
      '- 返回一个清理函数来处理卸载逻辑',
      '- useEffect(() => { return () => { cleanup } }, [])',
      '',
      '常见用途：',
      '- 数据获取（API 调用）',
      '- 设置订阅',
      '- 手动修改 DOM',
      '- 定时器管理',
    ],
  },
  {
    name: 'CustomHooks',
    title: '8. 自定义 Hooks',
    content: [
      '自定义 Hook 是以 "use" 开头的函数，可以调用其他 Hook。',
      '',
      '优势：',
      '- 逻辑复用：在多个组件间共享状态逻辑',
      '- 代码组织：将相关逻辑提取到独立的 Hook',
      '- 测试友好：可以单独测试 Hook 逻辑',
      '',
      '示例：',
      '- useLocalStorage：持久化数据到 localStorage',
      '- useFetch：封装数据获取逻辑',
      '- useDebounce：防抖处理',
      '- useWindowSize：监听窗口大小变化',
      '',
      '命名规范：',
      '- 必须以 "use" 开头',
      '- 遵循 Hook 规则',
    ],
  },
  {
    name: 'Context',
    title: '9. Context API',
    content: [
      'Context 提供了一种在组件树中传递数据的方式，无需逐层传递 props。',
      '',
      '使用场景：',
      '- 主题切换',
      '- 用户认证信息',
      '- 语言设置',
      '- 全局状态管理',
      '',
      '核心 API：',
      '- React.createContext()：创建 Context',
      '- Context.Provider：提供数据',
      '- useContext Hook：消费数据',
      '',
      '注意事项：',
      '- 避免过度使用，可能导致组件耦合',
      '- 适合低频更新的全局数据',
      '- 高频更新考虑使用状态管理库',
    ],
  },
  {
    name: 'Redux',
    title: '10. Redux 状态管理',
    content: [
      'Redux 是一个可预测的状态容器，用于管理大型应用的复杂状态。',
      '',
      '核心概念：',
      '- Store：存储应用状态的单一数据源',
      '- Action：描述发生了什么的普通对象',
      '- Reducer：根据 action 更新 state 的纯函数',
      '- Dispatch：发送 action 的方法',
      '',
      'Redux Toolkit（推荐）：',
      '- createSlice：简化 reducer 和 action 创建',
      '- configureStore：配置 store',
      '- createAsyncThunk：处理异步逻辑',
      '',
      '何时使用 Redux：',
      '- 应用状态复杂且频繁更新',
      '- 需要在多个不相关组件间共享状态',
      '- 需要时间旅行调试',
    ],
  },
  {
    name: 'Router',
    title: '11. React Router',
    content: [
      'React Router 是 React 应用的标准路由库。',
      '',
      '核心组件：',
      '- BrowserRouter：使用 HTML5 history API',
      '- Routes：定义路由规则',
      '- Route：单个路由配置',
      '- Link：导航链接',
      '- NavLink：带激活状态的链接',
      '- useNavigate：编程式导航',
      '- useParams：获取路由参数',
      '- useLocation：获取当前位置信息',
      '',
      '路由类型：',
      '- 静态路由：固定路径',
      '- 动态路由：包含参数（/user/:id）',
      '- 嵌套路由：路由嵌套结构',
      '- 保护路由：需要认证才能访问',
    ],
  },
  {
    name: 'Forms',
    title: '12. 表单处理',
    content: [
      'React 中有两种主要的表单处理方式：',
      '',
      '受控组件（Controlled）：',
      '- 表单数据由 React state 管理',
      '- 每次输入变化都更新 state',
      '- 完全控制表单行为',
      '- 适合需要实时验证的场景',
      '',
      '非受控组件（Uncontrolled）：',
      '- 表单数据由 DOM 自己管理',
      '- 使用 ref 获取表单值',
      '- 更简单，性能更好',
      '- 适合简单表单',
      '',
      '表单库推荐：',
      '- React Hook Form：高性能，最小重渲染',
      '- Formik：功能丰富，易于使用',
      '- Yup/Zod：表单验证 schema',
    ],
  },
  {
    name: 'Performance',
    title: '13. 性能优化',
    content: [
      'React 性能优化策略：',
      '',
      '1. 减少不必要的重渲染：',
      '- React.memo：记忆化组件',
      '- useMemo：记忆化计算结果',
      '- useCallback：记忆化回调函数',
      '',
      '2. 代码分割：',
      '- React.lazy：懒加载组件',
      '- Suspense：加载状态管理',
      '- 路由级别的代码分割',
      '',
      '3. 列表优化：',
      '- 使用唯一且稳定的 key',
      '- 虚拟列表（react-window）',
      '',
      '4. 其他优化：',
      '- 避免内联对象和函数',
      '- 使用生产构建',
      '- 图片懒加载',
      '- Web Worker 处理密集计算',
    ],
  },
  {
    name: 'Testing',
    title: '14. 测试',
    content: [
      'React 应用测试策略：',
      '',
      '测试类型：',
      '- 单元测试：测试单个函数或组件',
      '- 集成测试：测试多个组件协作',
      '- E2E 测试：测试完整用户流程',
      '',
      '测试工具：',
      '- Jest：JavaScript 测试框架',
      '- React Testing Library：测试 React 组件',
      '- Cypress/Playwright：E2E 测试',
      '',
      '测试最佳实践：',
      '- 测试用户行为，不是实现细节',
      '- 使用 describe/it 组织测试',
      '- 保持测试独立和可重复',
      '- 覆盖边界情况',
      '- 模拟外部依赖（API、定时器等）',
    ],
  },
  {
    name: 'TypeScript',
    title: '15. TypeScript 集成',
    content: [
      'TypeScript 为 React 添加类型安全。',
      '',
      '核心类型：',
      '- FC/PFC：函数组件类型',
      '- React.ReactNode：子节点类型',
      '- React.CSSProperties：样式类型',
      '- React.RefObject：ref 类型',
      '',
      'Props 类型定义：',
      '- interface：定义组件属性接口',
      '- type：类型别名',
      '- 泛型组件：支持多种类型',
      '',
      'Hook 类型：',
      '- useState<Type>(initialValue)',
      '- useRef<HTMLDivElement>(null)',
      '- useContext(ContextType)',
      '',
      '事件类型：',
      '- React.ChangeEvent<HTMLInputElement>',
      '- React.FormEvent<HTMLFormElement>',
      '- React.MouseEvent<HTMLButtonElement>',
    ],
  },
  {
    name: 'AdvancedPatterns',
    title: '16. 高级模式',
    content: [
      'React 高级设计模式：',
      '',
      '1. 高阶组件（HOC）：',
      '- 接收组件并返回新组件的函数',
      '- 用于逻辑复用和增强',
      '',
      '2. Render Props：',
      '- 通过 prop 传递渲染函数',
      '- 灵活的组件组合方式',
      '',
      '3. 复合组件：',
      '- 多个组件协同工作',
      '- 共享隐式状态',
      '',
      '4. 控制与非控制组件：',
      '- 控制组件：外部控制状态',
      '- 非控制组件：内部管理状态',
      '',
      '5. Error Boundaries：',
      '- 捕获子组件树中的错误',
      '- 显示降级 UI',
      '',
      '6. Portals：',
      '- 将子节点渲染到 DOM 其他位置',
      '- 适合模态框、tooltip 等',
    ],
  },
  {
    name: 'SSR',
    title: '17. 服务端渲染 (SSR)',
    content: [
      '服务端渲染在服务器上生成 HTML。',
      '',
      'SSR 优势：',
      '- 更好的 SEO：搜索引擎可以抓取内容',
      '- 更快的首屏加载：用户看到内容更快',
      '- 更好的社交分享：OG 标签正常工作',
      '',
      'SSR 框架：',
      '- Next.js：最流行的 React SSR 框架',
      '- Remix：专注于 Web 标准和用户体验',
      '- Gatsby：静态站点生成器',
      '',
      '渲染方式对比：',
      '- CSR（客户端渲染）：浏览器下载 JS 后渲染',
      '- SSR（服务端渲染）：服务器生成 HTML',
      '- SSG（静态生成）：构建时生成 HTML',
      '- ISR（增量静态再生）：混合 SSG 和 SSR',
      '',
      '水合（Hydration）：',
      '- 客户端接管服务端渲染的 HTML',
      '- 添加事件监听器和交互性',
    ],
  },
  {
    name: 'Ecosystem',
    title: '18. 生态系统',
    content: [
      'React 生态系统包含众多工具和库：',
      '',
      'UI 组件库：',
      '- Ant Design：企业级 UI 组件库',
      '- Material-UI：Google Material Design',
      '- Chakra UI：模块化且易用的组件库',
      '- Tailwind CSS：实用优先的 CSS 框架',
      '',
      '状态管理：',
      '- Redux / Redux Toolkit',
      '- Zustand：轻量级状态管理',
      '- Jotai：原子化状态管理',
      '- Recoil：Facebook 实验性状态管理',
      '',
      '数据获取：',
      '- React Query / TanStack Query',
      '- SWR：由 Vercel 开发',
      '- Apollo Client：GraphQL 客户端',
      '',
      '开发工具：',
      '- React DevTools：浏览器扩展',
      '- ESLint + eslint-plugin-react',
      '- Prettier：代码格式化',
      '- Vite / Create React App：项目脚手架',
      '',
      '部署平台：',
      '- Vercel：一键部署',
      '- Netlify：静态站点托管',
      '- AWS Amplify：云平台',
    ],
  },
]

export default pages
